version: '3.4'

services:

  payments.api:
    image: ${DOCKER_REGISTRY-}paymentsapi
    build:
      context: .
      dockerfile: Payments.API/Dockerfile
    ports:
      - 5001:5001
    volumes:
      - //c/PaymentGW/Logs:/Logs
      - //c/PaymentGW/Logs:/app/Logs
    depends_on:
      - sql.server

  payment.gateway:
    image: ${DOCKER_REGISTRY-}paymentgateway
    build:
      context: .
      dockerfile: Payment.Gateway/Dockerfile
    ports:
      - 5000:5000


  banking.simulator:
    image: ${DOCKER_REGISTRY-}bankingsimulator
    build:
      context: .
      dockerfile: Banking.Simulator/Dockerfile
    ports:
      - 5002:5002

  sql.server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1433:1433"   

